const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=process.env.PORT||3000, SECRET=process.env.JWT_SECRET||'CHANGE_ME_BEFORE_PRODUCTION';
const DB=path.join(__dirname,'data.json');
const seed={users:[],plans:[{id:1,name:'Starter',price:999,period:'month',features:['Weekly research','Basic alerts','Email notifications']},{id:2,name:'Pro',price:2499,period:'month',features:['Daily research','Buy/Sell alerts','Model portfolio','Priority support']},{id:3,name:'Premium',price:4999,period:'month',features:['All Pro features','1:1 review calls','Advanced portfolio tracking']}],research:[],calls:[],recommendations:[],portfolios:[],payments:[],notifications:[],kyc:[]};
function load(){if(!fs.existsSync(DB)){const admin={id:1,name:'Administrator',email:'admin@vertexadvisory.in',role:'admin',password:hash('Admin@12345')};seed.users=[admin];fs.writeFileSync(DB,JSON.stringify(seed,null,2));}return JSON.parse(fs.readFileSync(DB,'utf8'))}let db=load();function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))}
function hash(p){const s=crypto.randomBytes(16).toString('hex');const h=crypto.scryptSync(p,s,64).toString('hex');return s+':'+h}function verify(p,x){try{const [s,h]=x.split(':');return crypto.timingSafeEqual(Buffer.from(h,'hex'),crypto.scryptSync(p,s,64))}catch{return false}}
function b64(x){return Buffer.from(JSON.stringify(x)).toString('base64url')}function token(u){const h=b64({alg:'HS256',typ:'JWT'}),p=b64({id:u.id,email:u.email,role:u.role,name:u.name,exp:Date.now()+7*864e5});const s=crypto.createHmac('sha256',SECRET).update(h+'.'+p).digest('base64url');return h+'.'+p+'.'+s}function auth(req){const t=(req.headers.authorization||'').replace('Bearer ','');try{const [h,p,s]=t.split('.');const good=crypto.createHmac('sha256',SECRET).update(h+'.'+p).digest('base64url');if(s!==good)return null;const x=JSON.parse(Buffer.from(p,'base64url'));if(x.exp<Date.now())return null;return x}catch{return null}}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch{resolve({})}});req.on('error',reject)})}
function send(res,code,data){res.writeHead(code,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(data))}function publicUser(u){return {id:u.id,name:u.name,email:u.email,role:u.role,planId:u.planId||null}}
function id(arr){return arr.length?Math.max(...arr.map(x=>x.id||0))+1:1}
function notify(userId,title,message){db.notifications.push({id:id(db.notifications),userId,title,message,read:false,createdAt:new Date().toISOString()})}
async function api(req,res){const url=new URL(req.url,'http://localhost');const p=url.pathname; if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization'});return res.end()}
if(p==='/api/register'&&req.method==='POST'){const x=await body(req);if(!x.name||!x.email||!x.password||x.password.length<8)return send(res,400,{error:'Name, email and password (8+ characters) are required.'});if(db.users.some(u=>u.email===x.email.toLowerCase()))return send(res,409,{error:'Email already registered.'});const u={id:id(db.users),name:x.name,email:x.email.toLowerCase(),password:hash(x.password),role:'client',planId:null};db.users.push(u);db.kyc.push({id:id(db.kyc),userId:u.id,status:'not_submitted',documents:[],updatedAt:new Date().toISOString()});notify(u.id,'Welcome to Vertex Advisory','Complete your KYC and choose a subscription plan to activate your client profile.');save();return send(res,201,{token:token(u),user:publicUser(u)})}
if(p==='/api/login'&&req.method==='POST'){const x=await body(req),u=db.users.find(v=>v.email===String(x.email||'').toLowerCase());if(!u||!verify(x.password||'',u.password))return send(res,401,{error:'Invalid email or password.'});return send(res,200,{token:token(u),user:publicUser(u)})}
const me=auth(req);if(!me)return send(res,401,{error:'Authentication required.'});const u=db.users.find(v=>v.id===me.id);if(!u)return send(res,401,{error:'Account not found.'});
if(p==='/api/dashboard'&&req.method==='GET'){const k=db.kyc.find(x=>x.userId===u.id);return send(res,200,{user:publicUser(u),plans:db.plans,research:db.research,calls:db.calls.filter(x=>x.userId===u.id||x.userId==null),recommendations:db.recommendations,portfolio:db.portfolios.filter(x=>x.userId===u.id),payments:db.payments.filter(x=>x.userId===u.id),notifications:db.notifications.filter(x=>x.userId===u.id).sort((a,b)=>b.id-a.id),kyc:k})}
if(p==='/api/admin'&&req.method==='GET'){if(u.role!=='admin')return send(res,403,{error:'Admin only.'});return send(res,200,{users:db.users.map(publicUser),plans:db.plans,research:db.research,calls:db.calls,recommendations:db.recommendations,portfolio:db.portfolios,payments:db.payments,notifications:db.notifications,kyc:db.kyc})}
if(u.role!=='admin'&&p.startsWith('/api/admin'))return send(res,403,{error:'Admin only.'});
if(p==='/api/plan'&&req.method==='POST'){const x=await body(req);if(!db.plans.some(a=>a.id===+x.planId))return send(res,400,{error:'Invalid plan.'});u.planId=+x.planId;db.payments.push({id:id(db.payments),userId:u.id,planId:u.planId,amount:db.plans.find(a=>a.id===u.planId).price,status:'pending',method:x.method||'manual',createdAt:new Date().toISOString()});notify(u.id,'Plan selected','Your subscription request is pending payment confirmation.');save();return send(res,200,{ok:true})}
if(p==='/api/kyc'&&req.method==='POST'){const x=await body(req),k=db.kyc.find(a=>a.userId===u.id)||{id:id(db.kyc),userId:u.id};Object.assign(k,{status:x.status||'submitted',documents:x.documents||[],updatedAt:new Date().toISOString()});if(!db.kyc.includes(k))db.kyc.push(k);notify(u.id,'KYC submitted','Your KYC information has been submitted for review.');save();return send(res,200,{kyc:k})}
if(p==='/api/portfolio'&&req.method==='POST'){const x=await body(req);db.portfolios.push({id:id(db.portfolios),userId:u.id,symbol:x.symbol,quantity:+x.quantity||0,avgPrice:+x.avgPrice||0,updatedAt:new Date().toISOString()});save();return send(res,201,{ok:true})}
if(p==='/api/admin/research'&&req.method==='POST'){const x=await body(req);db.research.unshift({id:id(db.research),title:x.title,category:x.category||'Research',body:x.body,createdAt:new Date().toISOString()});save();return send(res,201,{ok:true})}
if(p==='/api/admin/recommendation'&&req.method==='POST'){const x=await body(req);db.recommendations.unshift({id:id(db.recommendations),symbol:x.symbol,action:x.action,entry:x.entry,target:x.target,stopLoss:x.stopLoss,risk:x.risk||'Medium',note:x.note||'',createdAt:new Date().toISOString()});db.users.filter(a=>a.role==='client').forEach(c=>notify(c.id,'New market recommendation',`${x.action} ${x.symbol} — target ${x.target||'N/A'}`));save();return send(res,201,{ok:true})}
if(p==='/api/admin/call'&&req.method==='POST'){const x=await body(req);db.calls.push({id:id(db.calls),userId:x.userId?+x.userId:null,date:x.date,time:x.time,topic:x.topic,status:'scheduled'});if(x.userId)notify(+x.userId,'Advisory call scheduled',`${x.date} ${x.time} — ${x.topic}`);save();return send(res,201,{ok:true})}
if(p==='/api/admin/payment'&&req.method==='POST'){const x=await body(req);const pay=db.payments.find(a=>a.id===+x.id);if(!pay)return send(res,404,{error:'Payment not found.'});pay.status=x.status||'paid';if(pay.status==='paid')notify(pay.userId,'Payment confirmed','Your subscription payment has been marked as paid.');save();return send(res,200,{ok:true})}
if(p==='/api/admin/kyc'&&req.method==='POST'){const x=await body(req);const k=db.kyc.find(a=>a.id===+x.id);if(!k)return send(res,404,{error:'KYC not found.'});k.status=x.status;k.updatedAt=new Date().toISOString();notify(k.userId,'KYC status updated',`Your KYC status is now ${k.status}.`);save();return send(res,200,{ok:true})}
if(p==='/api/admin/notification'&&req.method==='POST'){const x=await body(req);const recipients=x.userId?[+x.userId]:db.users.filter(a=>a.role==='client').map(a=>a.id);recipients.forEach(id=>notify(id,x.title,x.message));save();return send(res,201,{ok:true})}
if(p==='/api/admin/plan'&&req.method==='POST'){const x=await body(req);db.plans.push({id:id(db.plans),name:x.name,price:+x.price,period:x.period||'month',features:(x.features||'').split(',').map(s=>s.trim()).filter(Boolean)});save();return send(res,201,{ok:true})}
send(res,404,{error:'Not found'})}
const server=http.createServer(async(req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let file=req.url==='/'?'/index.html':req.url;file=path.normalize(file).replace(/^\.\.(\/|\\)/,'');const fp=path.join(__dirname,'public',file);if(!fp.startsWith(path.join(__dirname,'public')))return send(res,403,{error:'Forbidden'});fs.readFile(fp,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(fp);const ct={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'}[ext]||'text/plain';res.writeHead(200,{'Content-Type':ct});res.end(d)})});server.listen(PORT,'0.0.0.0',()=>console.log(`Vertex Advisory portal: http://localhost:${PORT}`));
